# Generated by Django 2.0.3 on 2018-09-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_commentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='reply_message',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
